-- Enable the CITEXT extension for case-insensitive columns
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email CITEXT NOT NULL UNIQUE,
    is_deleted BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT roles_name_length CHECK (length(name) <= 20)
);

CREATE TABLE permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name CITEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT permissions_name_length CHECK (length(name) <= 30)
);

INSERT INTO roles (name) VALUES
    ('guest'),
    ('registered-viewer'),
    ('registered-artist'),
    ('administrator');

INSERT INTO permissions (name) VALUES
    ('view_full_image'),
    ('view_gallery'),
    ('view_registered_user'),
    ('use_image_upload'),
    ('use_image_like'),
    ('use_image_download'),
    ('use_follow'),
    ('use_image_report'),
    ('use_image_report_comments'),
    ('use_image_report_close'),
    ('use_image_delete');